language: python
python: 3.6
sudo: false
branches:
  only:
  - master
  - develop
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=${HOME}/virtualenv/python3.6/src/briefy.gdrive/src/briefy/gdrive/private/briefy.gdrive-test-e9a853b36334.json
  matrix:
  - TOX_ENV=py36
  - TOX_ENV=lint
  - TOX_ENV=coverage

install:
- pip install -r requirements/dev.txt

script:
- tox -e $TOX_ENV

after_success:
- make docs
